DROP DATABASE IF EXISTS rastreabilidade;
CREATE DATABASE rastreabilidade;
USE rastreabilidade;

CREATE TABLE fornecedor (
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE 
,nome VARCHAR(100) NOT NULL  UNIQUE
,tipo_fruta VARCHAR(30) NOT NULL  
,produtos_utilizados VARCHAR(300) NOT NULL  
,cnpj VARCHAR(20) NOT NULL  UNIQUE
);

INSERT INTO fornecedor (nome,tipo_fruta,produtos_utilizados,cnpj) VALUES ('FAZENDA DO SEU ZÉ', 'LARANJA PERA', 'PROFF', '12.345.678/9101-23');
INSERT INTO fornecedor (nome,tipo_fruta,produtos_utilizados,cnpj) VALUES ('FAZENDA DO SEU FELIPE', 'LARANJA BAHIA', 'PROFF', '05.355.664/0001-97');
INSERT INTO fornecedor (nome,tipo_fruta,produtos_utilizados,cnpj) VALUES ('FAZENDA DO SEU JORGE', 'LARANJA LIMA', 'PROFF', '60.126.081/0001-00');

SELECT * FROM fornecedor;

CREATE TABLE transportadora (
id INT NOT NULL PRIMARY KEY UNIQUE AUTO_INCREMENT
,nome VARCHAR(100) NOT NULL
,cnpj VARCHAR(20) NOT NULL UNIQUE
);

INSERT INTO transportadora (nome,cnpj) VALUES ('TRANSPORTADORA HOT WELLS', '76.520.027/0001-77');
INSERT INTO transportadora (nome,cnpj) VALUES ('TRANSPORTADORA FAST TRUCK', '09.958.334/0001-47');
INSERT INTO transportadora (nome,cnpj) VALUES ('TRANSPORTADORA CAMINHAO RAPIDO', '51.219.355/0001-07');

SELECT * FROM transportadora;

CREATE TABLE fabrica (
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE
,nome VARCHAR(100) NOT NULL 
,cnpj VARCHAR(20) NOT NULL UNIQUE
,chegada_fruta DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO fabrica (nome, cnpj) VALUES ('FABRICA DE SUCO LARANJA', '80.061.328/0001-57');
INSERT INTO fabrica (nome, cnpj) VALUES ('FABRICA DE SUCO LARANJINHA', '97.890.249/0001-51');
INSERT INTO fabrica (nome, cnpj) VALUES ('FABRICA DE SUCO LARANJÃO', '56.348.348/0001-29');

SELECT * FROM fabrica;

CREATE TABLE processo (
id INT NOT NULL PRIMARY KEY UNIQUE AUTO_INCREMENT
,processo_extracao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
,processo_concentracao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
,processo_resfrigeracao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO processo (id) VALUES (1);
INSERT INTO processo (id) VALUES (2);
INSERT INTO processo (id) VALUES (3);

SELECT * FROM processo;

CREATE TABLE cliente( 
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE 
,nome_completo VARCHAR(100) NOT NULL UNIQUE
,cnpj VARCHAR(20) NOT NULL UNIQUE
);

INSERT INTO cliente (nome_completo,cnpj) VALUES ('JOSISVALDO JOSIAS DA SILVA','42.963.347/0001-80');
INSERT INTO cliente (nome_completo,cnpj) VALUES ('GRÉGORY SILVA','65.687.165/0001-29');
INSERT INTO cliente (nome_completo,cnpj) VALUES ('NELSON SANTOS','59.130.446/0001-83');

SELECT * FROM cliente;

CREATE TABLE cidade(
id INT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT
,nome VARCHAR(100) NOT NULL 
);

INSERT INTO cidade (nome) VALUES ('PARANAVAÍ');
INSERT INTO cidade (nome) VALUES ('MARINGA');
INSERT INTO cidade (nome) VALUES ('CURITIBA');

SELECT * FROM cidade;

CREATE TABLE estado (
id INT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT
,nome VARCHAR(100) NOT NULL
,sigla CHAR(2) NOT NULL
);

INSERT INTO estado (nome,sigla) VALUES ('PARANÁ','PR');
INSERT INTO estado (nome,sigla) VALUES ('SÃO PAULO','SP');
INSERT INTO estado (nome,sigla) VALUES ('RIO DE JANEIRO','RJ');

SELECT * FROM estado;

CREATE TABLE pais (
id INT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT
,nome VARCHAR(100) NOT NULL
);

INSERT INTO pais (nome) VALUES ('BRASIL');

SELECT * FROM pais;